[package]
name = "rust-tui-example"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
portmidi = "0.3.0"
toml = "0.8.19"
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
pulseaudio = "0.2.1"
byteorder = "1.5.0"
spectrum-analyzer = "1.6.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 2
debug = false
panic = "abort"
overflow-checks = false
