[package]
name = "rust-tui-example"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
portmidi = "0.3.0"
toml = "0.8.19"
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
nannou_audio = "0.19.0"
ringbuf = "0.4.7"
