["XONE:K2 "]
v2             = 25
spiral         = 24
waves          = 26
intensity      = 16
time_dialation = 19
reset          = 36 
backwards      = 37

["Arturia KeyLab Essential 61 MID"]
v2             = 40
spiral         = 41
intensity      = 73
reset          = 0
waves          = 26
time_dialation = 19
backwards      = 0
